docker run -d \
  --name crank-weston \
  --network host \
  --cap-add "CAP_SYS_TTY_CONFIG" \
  --volume "/dev:/dev" \
  --volume "/tmp:/tmp" \
  --volume "/run/udev/:/run/udev/" \
  --device-cgroup-rule "c 4:* rmw" \
  --device-cgroup-rule "c 13:* rmw" \
  --device-cgroup-rule "c 226:* rmw" $REGISTRY/torizon/crank-weston-am62:stable-rc --developer

docker run -d \
  --name crank-am62 \
  --device-cgroup-rule "c 226:* rmw" \
  --volume "/tmp:/tmp" \
  --volume "/var/run/dbus:/var/run/dbus" \
  --volume "/dev/dri:/dev/dri" $REGISTRY/cranksoftware/ti62-sb_8_2-wayland-base-am62_4:v0.1
