docker run -d \
  --network host \
  --cap-add "CAP_SYS_TTY_CONFIG" \
  --volume "/dev:/dev" \
  --volume "/tmp:/tmp" \
  --volume "/run/udev/:/run/udev/" \
  --device-cgroup-rule "c 4:* rmw" \
  --device-cgroup-rule "c 13:* rmw" \
  --device-cgroup-rule "c 226:* rmw" $REGISTRY/torizon/crank-weston-upstream:stable-rc --developer

docker run -d \
  --name crank \
  --interactive \
  --tty \
  --device-cgroup-rule "c 226:* rmw" \
  --volume "/tmp:/tmp" \
  --volume "/dev/dri:/dev/dri" \
  --volume "/var/run/dbus:/var/run/dbus" $REGISTRY/cranksoftware/imx6-sb_8_2-wayland-base_4:v0.2
