docker run -d \
  --name crank-weston \
  --network host \
  --cap-add "CAP_SYS_TTY_CONFIG" \
  --volume "/dev:/dev" \
  --volume "/tmp:/tmp" \
  --volume "/run/udev:/run/udev" \
  --device-cgroup-rule "c 4:* rmw" \
  --device-cgroup-rule "c 10:223 rmw" \
  --device-cgroup-rule "c 13:* rmw" \
  --device-cgroup-rule "c 199:0 rmw" \
  --device-cgroup-rule "c 226:* rmw" \
  --device-cgroup-rule "c 253:* rmw" $REGISTRY/torizon/crank-weston-imx8:stable-rc --tty=/dev/tty7

docker run -d \
  --name crank \
  --device-cgroup-rule "c 199:* rmw" \
  --interactive \
  --tty \
  --volume "/tmp:/tmp" \
  --volume "/var/run/dbus:/var/run/dbus" \
  --volume "/dev/galcore:/dev/galcore" $REGISTRY/cranksoftware/imx8-sb_8_2-wayland-base-imx8_4:v0.1
