[core]
idle-time=0
require-input=false
xwayland=true
modules=screen-share.so
# uncomment line below to use kiosk shell
#shell=kiosk-shell.so

[shell]
panel-position=top
locking=false
allow-zap=true
num-workspaces=1

[output]
name=HDMI-A-1
# uncomment line below to set an output resolution. Run for example 'cat /sys/class/drm/card1-HDMI-A-1/modes' to list the available modes.
mode=1280x720@60

[output]
name=HDMI-A-2
# uncomment line below to set an output resolution. Run for example 'cat /sys/class/drm/card1-HDMI-A-1/modes' to list the available modes.
mode=1280x720@60
