docker run -d \
  --device-cgroup-rule "c 4:0 rmw" \
  --device-cgroup-rule "c 4:7 rmw" \
  --device-cgroup-rule "c 13:* rmw" \
  --device-cgroup-rule "c 199:* rmw" \
  --device-cgroup-rule "c 226:* rmw" \
  --volume "/dev:/dev" \
  --volume "/tmp:/tmp" embeddedwizard/ew-demo:ewdemo-verdin_am62p

docker run -d \
  --network host \
  --cap-add "CAP_SYS_TTY_CONFIG" \
  --volume "/dev:/dev" \
  --volume "/tmp:/tmp" \
  --volume "/run/udev:/run/udev" \
  --device-cgroup-rule "c 4:0 rmw" \
  --device-cgroup-rule "c 4:1 rmw" \
  --device-cgroup-rule "c 4:7 rmw" \
  --device-cgroup-rule "c 13:* rmw" \
  --device-cgroup-rule "c 199:* rmw" \
  --device-cgroup-rule "c 226:* rmw" \
  --env "ACCEPT_FSL_EULA=1" $REGISTRY/torizon/weston-am62p:stable-rc
