docker run -d \
  --name embedded-wizard-imx95 \
  --volume "/dev:/dev" \
  --volume "/tmp:/tmp" \
  --device-cgroup-rule "c 4:* rmw" \
  --device-cgroup-rule "c 10:* rmw" \
  --device-cgroup-rule "c 13:* rmw" \
  --device-cgroup-rule "c 199:* rmw" \
  --device-cgroup-rule "c 226:* rmw" \
  --device-cgroup-rule "c 253:* rmw" embeddedwizard/ew-demo:ewdemo-verdin_imx95

docker run -d \
  --network host \
  --cap-add "CAP_SYS_TTY_CONFIG" \
  --volume "/dev:/dev" \
  --volume "/tmp:/tmp" \
  --volume "/run/udev:/run/udev" \
  --device-cgroup-rule "c 4:* rmw" \
  --device-cgroup-rule "c 10:* rmw" \
  --device-cgroup-rule "c 13:* rmw" \
  --device-cgroup-rule "c 199:* rmw" \
  --device-cgroup-rule "c 226:* rmw" \
  --device-cgroup-rule "c 253:* rmw" \
  --env "ACCEPT_FSL_EULA=1" $REGISTRY/torizon/weston-imx95:stable-rc
