#!/usr/bin/env bash

# Streams H.264 video through RTP over UDP.
#
# The send mode extracts H.264 video from an MP4 file, packetizes it as RTP,
# sends it through UDP, and records a checksum for every transmitted packet.
# The receive mode records the received RTP packet checksums and reconstructs
# an H.264 elementary stream. The verify mode compares the sent and received
# packet sequences. The loopback mode runs all three operations end to end.

set -euo pipefail

readonly DEFAULT_HOST="127.0.0.1"
readonly DEFAULT_PORT="5000"
readonly DEFAULT_DURATION="30"
readonly RECEIVER_STARTUP_DELAY="1"
readonly RTP_CAPS="application/x-rtp,media=video,clock-rate=90000,encoding-name=H264,payload=96"

loopback_receiver_pid=""
loopback_tmpdir=""

usage() {
  cat <<EOF
Usage:
  $(basename "$0") send \
    --input <file.mp4> \
    --checksums <sent.sha256> \
    [options]

  $(basename "$0") receive \
    --output <file.h264> \
    --checksums <received.sha256> \
    [options]

  $(basename "$0") verify \
    --sent-checksums <sent.sha256> \
    --received-checksums <received.sha256>

  $(basename "$0") loopback \
    --input <file.mp4> \
    --output <file.h264> \
    [options]

Send options:
  --input FILE
      MP4 file containing an H.264 video stream.

  --checksums FILE
      File in which sent RTP packet checksums are stored.

  --host HOST
      Destination host.
      Default: ${DEFAULT_HOST}

  --port PORT
      Destination UDP port.
      Default: ${DEFAULT_PORT}

Receive options:
  --output FILE
      Destination H.264 elementary stream.

  --checksums FILE
      File in which received RTP packet checksums are stored.

  --port PORT
      UDP port on which to listen.
      Default: ${DEFAULT_PORT}

  --duration SECONDS
      Maximum time to receive packets.
      Default: ${DEFAULT_DURATION}

Verify options:
  --sent-checksums FILE
      Checksums generated by send mode.

  --received-checksums FILE
      Checksums generated by receive mode.

Loopback options:
  --input FILE
      MP4 file containing an H.264 video stream.

  --output FILE
      Destination H.264 elementary stream.

  --port PORT
      UDP loopback port.
      Default: ${DEFAULT_PORT}

  --duration SECONDS
      Maximum receiver execution time.
      Default: ${DEFAULT_DURATION}

General:
  -h, --help
      Show this help message.
EOF
}

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

require_command() {
  local command_name="$1"

  command -v "$command_name" >/dev/null 2>&1 ||
    fail "Required command is unavailable: $command_name"
}

require_element() {
  local element="$1"

  gst-inspect-1.0 "$element" >/dev/null 2>&1 ||
    fail "Required GStreamer element is unavailable: $element"
}

validate_positive_integer() {
  local value="$1"
  local argument="$2"

  [[ "$value" =~ ^[1-9][0-9]*$ ]] ||
    fail "$argument must be a positive integer: $value"
}

validate_port() {
  validate_positive_integer "$port" "--port"

  if ((port > 65535)); then
    fail "--port must be between 1 and 65535: $port"
  fi
}

validate_readable_file() {
  local file="$1"
  local argument="$2"

  [[ -n "$file" ]] ||
    fail "$argument is required"

  [[ -f "$file" ]] ||
    fail "File does not exist for $argument: $file"

  [[ -r "$file" ]] ||
    fail "File is not readable for $argument: $file"

  [[ -s "$file" ]] ||
    fail "File is empty for $argument: $file"
}

validate_destination_file() {
  local file="$1"
  local argument="$2"
  local directory

  [[ -n "$file" ]] ||
    fail "$argument is required"

  directory="$(dirname "$file")"

  [[ -d "$directory" ]] ||
    fail "Destination directory does not exist for $argument: $directory"

  [[ -w "$directory" ]] ||
    fail "Destination directory is not writable for $argument: $directory"
}

validate_distinct_files() {
  local first_file="$1"
  local first_argument="$2"
  local second_file="$3"
  local second_argument="$4"

  if [[ "$first_file" == "$second_file" ]]; then
    fail "$first_argument and $second_argument must use different files"
  fi
}

count_checksums() {
  local file="$1"

  wc -l <"$file" | tr -d '[:space:]'
}

cleanup_loopback() {
  local previous_status=$?

  if [[ -n "$loopback_receiver_pid" ]] &&
    kill -0 "$loopback_receiver_pid" >/dev/null 2>&1; then
    kill "$loopback_receiver_pid" >/dev/null 2>&1 || true
    wait "$loopback_receiver_pid" >/dev/null 2>&1 || true
  fi

  if [[ -n "$loopback_tmpdir" && -d "$loopback_tmpdir" ]]; then
    rm -rf "$loopback_tmpdir"
  fi

  return "$previous_status"
}

send_stream() {
  local packet_count
  local pipeline_statuses
  local gstreamer_status
  local awk_status

  validate_port
  validate_readable_file "$input_file" "--input"
  validate_destination_file "$checksums_file" "--checksums"

  [[ -n "$host" ]] ||
    fail "--host cannot be empty"

  require_command "gst-launch-1.0"
  require_command "gst-inspect-1.0"
  require_command "awk"
  require_command "wc"
  require_command "tr"

  require_element "filesrc"
  require_element "qtdemux"
  require_element "queue"
  require_element "h264parse"
  require_element "rtph264pay"
  require_element "tee"
  require_element "udpsink"
  require_element "checksumsink"

  rm -f "$checksums_file"

  echo "Streaming mode: send"
  echo "Input MP4 file: $input_file"
  echo "Destination: ${host}:${port}"
  echo "RTP checksums file: $checksums_file"

  set +e

  gst-launch-1.0 -q -e \
    filesrc location="$input_file" \
    ! qtdemux name=demux \
    demux.video_0 \
    ! queue \
    ! h264parse \
    ! rtph264pay config-interval=-1 aggregate-mode=none pt=96 \
    ! tee name=rtp \
    rtp. \
    ! queue \
    ! udpsink host="$host" port="$port" sync=true \
    rtp. \
    ! queue \
    ! checksumsink hash=sha256 sync=false |
    awk '
      length($2) == 64 && $2 ~ /^[0-9a-fA-F]+$/ {
        print tolower($2)
      }
    ' >"$checksums_file"

  pipeline_statuses=("${PIPESTATUS[@]}")

  set -e

  gstreamer_status="${pipeline_statuses[0]:-1}"
  awk_status="${pipeline_statuses[1]:-1}"

  if [[ "$gstreamer_status" -ne 0 ]]; then
    fail "The sending pipeline failed with status $gstreamer_status"
  fi

  if [[ "$awk_status" -ne 0 ]]; then
    fail "Failed to record sent RTP packet checksums"
  fi

  [[ -s "$checksums_file" ]] ||
    fail "No sent RTP packet checksums were generated"

  packet_count="$(count_checksums "$checksums_file")"

  echo "Sent RTP packets: $packet_count"
  echo "H.264 stream sent successfully"
  echo "Result: PASS"
}

receive_stream() {
  local packet_count
  local pipeline_statuses
  local gstreamer_status
  local awk_status

  validate_port
  validate_positive_integer "$duration" "--duration"
  validate_destination_file "$output_file" "--output"
  validate_destination_file "$checksums_file" "--checksums"

  validate_distinct_files \
    "$output_file" "--output" \
    "$checksums_file" "--checksums"

  require_command "gst-launch-1.0"
  require_command "gst-inspect-1.0"
  require_command "timeout"
  require_command "awk"
  require_command "wc"
  require_command "tr"
  require_command "stat"

  require_element "udpsrc"
  require_element "rtpjitterbuffer"
  require_element "tee"
  require_element "queue"
  require_element "rtph264depay"
  require_element "h264parse"
  require_element "filesink"
  require_element "checksumsink"

  rm -f "$output_file" "$checksums_file"

  echo "Streaming mode: receive"
  echo "Listening port: $port"
  echo "Receive duration: ${duration}s"
  echo "Output file: $output_file"
  echo "RTP checksums file: $checksums_file"

  set +e

  timeout \
    --signal=INT \
    --kill-after=10s \
    "${duration}s" \
    gst-launch-1.0 -q -e \
    udpsrc port="$port" caps="$RTP_CAPS" \
    ! rtpjitterbuffer latency=100 do-lost=true \
    ! tee name=rtp \
    rtp. \
    ! queue \
    ! rtph264depay \
    ! h264parse \
    ! "video/x-h264,stream-format=byte-stream,alignment=au" \
    ! filesink location="$output_file" sync=false \
    rtp. \
    ! queue \
    ! checksumsink hash=sha256 sync=false |
    awk '
      length($2) == 64 && $2 ~ /^[0-9a-fA-F]+$/ {
        print tolower($2)
      }
    ' >"$checksums_file"

  pipeline_statuses=("${PIPESTATUS[@]}")

  set -e

  gstreamer_status="${pipeline_statuses[0]:-1}"
  awk_status="${pipeline_statuses[1]:-1}"

  case "$gstreamer_status" in
    0) ;;

    124 | 130)
      echo "Receiver stopped after the configured duration"
      ;;

    137)
      echo "Receiver was force-stopped after the timeout grace period"
      ;;

    *)
      fail "The receiving pipeline failed with status $gstreamer_status"
      ;;
  esac

  if [[ "$awk_status" -ne 0 ]]; then
    fail "Failed to record received RTP packet checksums"
  fi

  [[ -s "$output_file" ]] ||
    fail "No H.264 data was received"

  [[ -s "$checksums_file" ]] ||
    fail "No received RTP packet checksums were generated"

  packet_count="$(count_checksums "$checksums_file")"

  echo "Received bytes: $(stat -c '%s' "$output_file")"
  echo "Received RTP packets: $packet_count"
  echo "H.264 stream received successfully"
  echo "Result: PASS"
}

verify_stream() {
  local sent_count
  local received_count

  validate_readable_file "$sent_checksums_file" "--sent-checksums"
  validate_readable_file "$received_checksums_file" "--received-checksums"

  validate_distinct_files \
    "$sent_checksums_file" "--sent-checksums" \
    "$received_checksums_file" "--received-checksums"

  require_command "cmp"
  require_command "wc"
  require_command "tr"

  sent_count="$(count_checksums "$sent_checksums_file")"
  received_count="$(count_checksums "$received_checksums_file")"

  echo "Streaming mode: verify"
  echo "Sent RTP packets: $sent_count"
  echo "Received RTP packets: $received_count"

  if [[ "$sent_count" -ne "$received_count" ]]; then
    fail \
      "RTP packet count differs: sent=$sent_count received=$received_count"
  fi

  if ! cmp -s "$sent_checksums_file" "$received_checksums_file"; then
    fail "Received RTP packet checksums do not match the sent packet checksums"
  fi

  echo "All RTP packets were received in the correct order"
  echo "RTP packet contents match successfully"
  echo "Result: PASS"
}

loopback_stream() {
  local receiver_log
  local sent_checksums
  local received_checksums
  local sender_status
  local receiver_status

  validate_port
  validate_positive_integer "$duration" "--duration"
  validate_readable_file "$input_file" "--input"
  validate_destination_file "$output_file" "--output"

  require_command "mktemp"
  require_command "sleep"
  require_command "cat"
  require_command "rm"

  loopback_tmpdir="$(mktemp -d /tmp/gstreamer-stream-loopback.XXXXXX)"
  receiver_log="$loopback_tmpdir/receiver.log"
  sent_checksums="$loopback_tmpdir/sent-rtp.sha256"
  received_checksums="$loopback_tmpdir/received-rtp.sha256"

  rm -f "$output_file"

  trap cleanup_loopback EXIT
  trap 'exit 130' INT
  trap 'exit 143' TERM

  echo "Streaming mode: loopback"
  echo "Input MP4 file: $input_file"
  echo "Output H.264 file: $output_file"
  echo "Loopback address: 127.0.0.1"
  echo "UDP port: $port"

  "$0" receive \
    --output "$output_file" \
    --checksums "$received_checksums" \
    --port "$port" \
    --duration "$duration" \
    >"$receiver_log" 2>&1 &

  loopback_receiver_pid=$!

  sleep "$RECEIVER_STARTUP_DELAY"

  if ! kill -0 "$loopback_receiver_pid" >/dev/null 2>&1; then
    receiver_status=0
    wait "$loopback_receiver_pid" || receiver_status=$?

    cat "$receiver_log"

    fail "The RTP receiver stopped before the sender started with status $receiver_status"
  fi

  sender_status=0

  "$0" send \
    --input "$input_file" \
    --checksums "$sent_checksums" \
    --host 127.0.0.1 \
    --port "$port" ||
    sender_status=$?

  if [[ "$sender_status" -ne 0 ]]; then
    cat "$receiver_log"
    fail "The RTP sender failed with status $sender_status"
  fi

  receiver_status=0
  wait "$loopback_receiver_pid" || receiver_status=$?
  loopback_receiver_pid=""

  cat "$receiver_log"

  if [[ "$receiver_status" -ne 0 ]]; then
    fail "The RTP receiver failed with status $receiver_status"
  fi

  "$0" verify \
    --sent-checksums "$sent_checksums" \
    --received-checksums "$received_checksums"

  echo "H.264 RTP UDP loopback completed successfully"
  echo "Result: PASS"

  rm -rf "$loopback_tmpdir"
  loopback_tmpdir=""

  trap - EXIT INT TERM
}

mode="${1:-}"

case "$mode" in
  send | receive | verify | loopback)
    shift
    ;;

  -h | --help)
    usage
    exit 0
    ;;

  "")
    usage >&2
    exit 1
    ;;

  *)
    fail "Unsupported mode: $mode"
    ;;
esac

host="$DEFAULT_HOST"
port="$DEFAULT_PORT"
duration="$DEFAULT_DURATION"

input_file=""
output_file=""
checksums_file=""
sent_checksums_file=""
received_checksums_file=""

while (($# > 0)); do
  case "$1" in
    --input)
      (($# >= 2)) || fail "Missing value for --input"
      input_file="$2"
      shift 2
      ;;

    --output)
      (($# >= 2)) || fail "Missing value for --output"
      output_file="$2"
      shift 2
      ;;

    --checksums)
      (($# >= 2)) || fail "Missing value for --checksums"
      checksums_file="$2"
      shift 2
      ;;

    --sent-checksums)
      (($# >= 2)) || fail "Missing value for --sent-checksums"
      sent_checksums_file="$2"
      shift 2
      ;;

    --received-checksums)
      (($# >= 2)) || fail "Missing value for --received-checksums"
      received_checksums_file="$2"
      shift 2
      ;;

    --host)
      (($# >= 2)) || fail "Missing value for --host"
      host="$2"
      shift 2
      ;;

    --port)
      (($# >= 2)) || fail "Missing value for --port"
      port="$2"
      shift 2
      ;;

    --duration)
      (($# >= 2)) || fail "Missing value for --duration"
      duration="$2"
      shift 2
      ;;

    -h | --help)
      usage
      exit 0
      ;;

    *)
      fail "Unknown argument: $1"
      ;;
  esac
done

case "$mode" in
  send)
    send_stream
    ;;

  receive)
    receive_stream
    ;;

  verify)
    verify_stream
    ;;

  loopback)
    loopback_stream
    ;;
esac
