docker run -d \
  --network host \
  --cap-add "CAP_SYS_TTY_CONFIG" \
  --volume "/dev:/dev" \
  --volume "/tmp:/tmp" \
  --volume "/run/udev/:/run/udev/" \
  --device-cgroup-rule "c 4:* rmw" \
  --device-cgroup-rule "c 13:* rmw" \
  --device-cgroup-rule "c 226:* rmw" $REGISTRY/torizon/weston-am62:stable-rc --developer

docker run -d \
  --device-cgroup-rule "c 226:* rmw" \
  --security-opt "seccomp:unconfined" \
  --shm-size 256mb \
  --interactive \
  --tty \
  --volume "/tmp:/tmp" \
  --volume "/var/run/dbus:/var/run/dbus" \
  --volume "/dev/dri:/dev/dri" $REGISTRY/torizon/chromium-tests-am62:stable-rc
