docker run -d \
  --network host \
  --cap-add "CAP_SYS_TTY_CONFIG" \
  --volume "/dev:/dev" \
  --volume "/tmp:/tmp" \
  --volume "/run/udev/:/run/udev/" \
  --device-cgroup-rule "c 4:* rmw" \
  --device-cgroup-rule "c 13:* rmw" \
  --device-cgroup-rule "c 226:* rmw" $REGISTRY/torizon/weston:stable-rc --developer

docker run -d \
  --device-cgroup-rule "c 226:* rmw" \
  --volume "/tmp:/tmp" \
  --volume "/dev/dri:/dev/dri" $REGISTRY/torizon/qt5-wayland-examples:stable-rc sh -c '
  arch="$(uname -m)"
  case "$$arch" in
    x86_64)  TRIPLET="x86_64-linux-gnu" ;;
    aarch64) TRIPLET="aarch64-linux-gnu" ;;
    armv7l)  TRIPLET="arm-linux-gnueabihf" ;;
    *)
      echo "Unsupported architecture: $$arch" >&2
      exit 1
      ;;
  esac
  exec /usr/lib/$$TRIPLET/qt5/examples/widgets/widgets/calculator/calculator
'

