docker run -d \
  --network host \
  --cap-add "CAP_SYS_TTY_CONFIG" \
  --volume "/dev:/dev" \
  --volume "/tmp:/tmp" \
  --volume "/run/udev/:/run/udev/" \
  --device-cgroup-rule "c 4:* rmw" \
  --device-cgroup-rule "c 13:* rmw" \
  --device-cgroup-rule "c 226:* rmw" $REGISTRY/torizon/weston-imx93:stable-rc --developer --tty=/dev/tty7

docker run -d \
  --device-cgroup-rule "c 226:* rmw" \
  --volume "/tmp:/tmp" $REGISTRY/torizon/qt5-wayland-examples-imx93:stable-rc /usr/lib/aarch64-linux-gnu/qt5/examples/widgets/widgets/calculator/calculator
