docker run -d \
  --name weston \
  --network host \
  --cap-add "CAP_SYS_TTY_CONFIG" \
  --volume "/dev:/dev" \
  --volume "/tmp:/tmp" \
  --volume "/run/udev/:/run/udev/" \
  --device-cgroup-rule "c 4:* rmw" \
  --device-cgroup-rule "c 13:* rmw" \
  --device-cgroup-rule "c 226:* rmw" \
  --device-cgroup-rule "c 10:223 rmw" $REGISTRY/torizon/weston-am62p:stable-rc --developer

docker run -d \
  --name lvgl - XDG_RUNTIME_DIR=/tmp \
  --device-cgroup-rule "c 226:* rmw" \
  --volume "/tmp:/tmp" \
  --volume "/var/run/dbus:/var/run/dbus" \
  --volume "/dev:/dev" ghcr.io/andrecostaaa/lv_demo_truck:latest
