docker run -d \
  --network host \
  --cap-add "CAP_SYS_TTY_CONFIG" \
  --volume "/dev:/dev" \
  --volume "/tmp:/tmp" \
  --volume "/run/udev/:/run/udev/" \
  --device-cgroup-rule "c 4:* rmw" \
  --device-cgroup-rule "c 253:* rmw" \
  --device-cgroup-rule "c 13:* rmw" \
  --device-cgroup-rule "c 226:* rmw" \
  --device-cgroup-rule "c 10:223 rmw" \
  --device-cgroup-rule "c 199:0 rmw" $REGISTRY/torizon/weston-imx8:stable-rc --developer --tty=/dev/tty7

docker run -d \
  --device-cgroup-rule "c 199:* rmw" \
  --volume "/tmp:/tmp" \
  --volume "/dev/galcore:/dev/galcore" $REGISTRY/torizon/qt6-enterprise-demo-imx8:stable-rc /opt/b2qt-demolauncher/qtlauncher
